baseURL = "https://howtokillachinaman.juliusreade.com/"
languageCode = "en-gb"
title = "How to kill a Chinaman"
theme = "reade"

googleAnalytics = "UA-85083093-3"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "#YOLO."
  images = ["images/htkac/cover_alt.png"]
  title = "How to kill a Chinaman"
